### ISSUE TITLE
[@pigi/contracts] Test Contracts

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/pigi#159]
Our contracts need to be tested, of course. Goals:

- [x] Set up a clean testing environment that takes advantage of TypeScript and minimizes duplicated code.
- [x] Determine if we need a more complex framework for testing plasma interactions.
- [ ] Hit 100% code coverage.
- [ ] Determine where fuzz testing is necessary.
- [ ] Use any available formal verification tools.
